name: Continuous Integration

on: [pull_request, workflow_dispatch]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: >
          DOCKER_BUILDKIT=1 docker build .
          --progress=plain
          --target=unit_test
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: >
          DOCKER_BUILDKIT=1 docker build
          --progress=plain
          --build-arg CONDUCTOR_SERVER_URL=${{ secrets.CONDUCTOR_SERVER_URL }}
          --target=test          
          .
